/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stelluxstudios_Shogi_Engine */

#ifndef _Included_com_stelluxstudios_Shogi_Engine
#define _Included_com_stelluxstudios_Shogi_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stelluxstudios_Shogi_Engine
 * Method:    newGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stelluxstudios_Shogi_Engine_newGame
  (JNIEnv *, jobject);

/*
 * Class:     com_stelluxstudios_Shogi_Engine
 * Method:    applyMove
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_stelluxstudios_Shogi_Engine_applyMove
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_stelluxstudios_Shogi_Engine
 * Method:    makeMove
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_stelluxstudios_Shogi_Engine_makeMove
  (JNIEnv *, jobject);

/*
 * Class:     com_stelluxstudios_Shogi_Engine
 * Method:    getBoardString
 * Signature: ()[B
 */
JNIEXPORT void JNICALL Java_com_stelluxstudios_Shogi_Engine_getBoardString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
