/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stelluxstudios_Shogi_Engine */

#ifndef _Included_com_stelluxstudios_Shogi_Engine
#define _Included_com_stelluxstudios_Shogi_Engine
#ifdef __cplusplus
extern "C" {
#endif

void Java_com_stelluxstudios_Shogi_Engine_initialize
  (JNIEnv *, jobject, jint);
/*
 * Class:     com_stelluxstudios_Shogi_Engine
 * Method:    newGame
 */
void Java_com_stelluxstudios_Shogi_Engine_newGame
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_stelluxstudios_Shogi_Engine
 * Method:    tryApplyMove
 */
  jint Java_com_stelluxstudios_Shogi_Engine_tryApplyMove
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_stelluxstudios_Shogi_Engine
 * Method:    makeMove
 */
 jint Java_com_stelluxstudios_Shogi_Engine_makeMove
  (JNIEnv *, jobject);
  
   jint Java_com_stelluxstudios_Shogi_Engine_getGameStatus
  (JNIEnv *, jobject);
  
   jint Java_com_stelluxstudios_Shogi_Engine_getCurrentPlayer
  (JNIEnv *, jobject);

/*
 * Class:     com_stelluxstudios_Shogi_Engine
 * Method:    getBoardString
 */
void Java_com_stelluxstudios_Shogi_Engine_getBoardString
  (JNIEnv *, jobject);
  
    jint Java_com_stelluxstudios_Shogi_Engine_saveToFile
  (JNIEnv *, jobject);
  
    jint Java_com_stelluxstudios_Shogi_Engine_loadFromFile
  (JNIEnv *, jobject);
  
  jstring Java_com_stelluxstudios_Shogi_Engine_getLastMove
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
