/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stelluxstudios_Shogi_Engine */

#ifndef _Included_com_stelluxstudios_Shogi_Engine
#define _Included_com_stelluxstudios_Shogi_Engine
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_stelluxstudios_Shogi_Engine_initialize
  (JNIEnv *, jobject);
/*
 * Class:     com_stelluxstudios_Shogi_Engine
 * Method:    newGame
 */
JNIEXPORT void JNICALL Java_com_stelluxstudios_Shogi_Engine_newGame
  (JNIEnv *, jobject);

/*
 * Class:     com_stelluxstudios_Shogi_Engine
 * Method:    tryApplyMove
 */
JNIEXPORT  jint JNICALL Java_com_stelluxstudios_Shogi_Engine_tryApplyMove
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_stelluxstudios_Shogi_Engine
 * Method:    makeMove
 */
JNIEXPORT jint JNICALL Java_com_stelluxstudios_Shogi_Engine_makeMove
  (JNIEnv *, jobject);
  
  JNIEXPORT jint JNICALL Java_com_stelluxstudios_Shogi_Engine_getGameStatus
  (JNIEnv *, jobject);
  
  JNIEXPORT jint JNICALL Java_com_stelluxstudios_Shogi_Engine_getCurrentPlayer
  (JNIEnv *, jobject);

/*
 * Class:     com_stelluxstudios_Shogi_Engine
 * Method:    getBoardString
 */
JNIEXPORT void JNICALL Java_com_stelluxstudios_Shogi_Engine_getBoardString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
